### ISSUE TITLE
Unable to upload multiple JSONs at once in admin console

### ISSUE THREAD

**Issue by Kevinsomnia** [heroiclabs/nakama#2385]
This is a regression with the new dashboard UI, since you're only able to select one JSON at a time to import to storage with the latest release (v3.31.0). In v3.29.0 and earlier, dragging and dropping multiple files worked.

Currently, we're working around it by using a Python script to do that for us, since we organize objects from different collections into separate JSONs.

There's also a typo on that `Data Management` page "bellow".
<img width="205" height="61" alt="Image" src="https://github.com/user-attachments/assets/f35ea600-8cd2-4923-8e7c-76bf490b7b10" />

**Comment by novabyte** [comment]
Thanks for the feedback @Kevinsomnia. We'll add this flexibility back in with an upcoming release.

**Comment by jpntex** [comment]
This was fixed in the [v3.33.0](https://github.com/heroiclabs/nakama/releases/tag/v3.33.0) release, please let us know if you find any issues.

**Comment by Kevinsomnia** [comment]
I tried to upload multiple files on my local Nakama server (running `v3.34.0`), but only the first upload succeeds even though it says `Upload failed. Status: 200`. The network tab in the browser devtools also confirms that it is returning a 200 status code. Our Python script for multi-file upload is also failing with the same error.

On the server logs, we're seeing
```
{"level":"warn","caller":"server/console_storage_import.go:205","msg":"Failed to write imported records.","trace_id":"8faeaea4-ee4a-4cdc-8e87-f5c9e263fff1","error":"Storage write rejected - version check failed."}
```

**Comment by Kevinsomnia** [comment]
@jpntex Any update on this issue? We're still seeing this error from the message above on 3.35.1. We won't be able to update since even the Python script we were using is broken.
